<a href="https://colab.research.google.com/github/simonoconnor2022/UCD-Upload-Practice-/blob/main/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Upload csv file of Irish Attractions from laptop

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Attractions (1).csv to Attractions (1).csv

In [ ]:
#import pandas

In [2]:
import pandas as pd

In [ ]:
#write code inorder to read the uploaded Attractions (1) file

In [ ]:
#Create Data Frame with relevevant headers

In [3]:
path = "Attractions (1).csv"

df = pd.read_csv(path)

df #displays dataframe

,Name,Url,Telephone,Longitude,Latitude,AddressRegion,AddressLocality,AddressCountry,Tags
0,Ireland Writing Retreat Donegal,https://www.irelandwritingretreat.com,3.53833E+11,-8.232855,55.051496,Donegal,Gweedore,Ireland,"Learning,Activity Operator,Literary Ireland"
1,Swords Castle,https://swordscastle.events/,+353(0)1840 0891,-6.220338,53.459928,Dublin,Swords,Republic of Ireland,"Historic Houses and Castle,Castle,Tour"
2,Kilbolane Castle,https://visitballyhoura.com/explore/kilbolane-...,3536391300,-8.846867,52.337725,Cork,NaN,Ireland,"Historic Houses and Castle,Castle"
3,Spanish Point,NaN,NaN,-9.432739,52.842867,Clare,Spanish Point,Ireland,Discovery Point
4,Dunloe Castle,https://killarney.ie/listing/dunloe-castle,3.53647E+11,-9.627419,52.059671,Kerry,Beaufort,Republic of Ireland,"Castle,Historic Houses and Castle"
...,...,...,...,...,...,...,...,...,...
539,Macroom Buffalo Farm with O'Tuama Tours,https://www.otuamatours.ie,3.53869E+11,-9.247536,51.850410,Cork,Ballingeary,Republic of Ireland,"Food and Drink,Restaurant,Activity Operator,Vi..."
540,The Back Lane Pop Up Gallery,http://thebacklanegallery.blogspot.com/,3.53873E+11,-9.506293,52.058996,Kerry,Killarney,Ireland,"Craft,Shopping,Art Gallery"
541,Ferns Cathedral,https://www.archaeology.ie/monument-of-the-mon...,NaN,-6.492614,52.589983,Wexford,NaN,Ireland,"Church Abbey,Monastery,Churches,Abbeys and Mon..."
542,The Spire,NaN,NaN,-6.260294,53.350921,Dublin,Dublin City,Ireland,Public Sculpture
543,Courtown Beach,NaN,NaN,-6.226047,52.647958,Wexford,Courtown,Ireland,Beach

In [4]:
# Understand the data that has been uploaded

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             544 non-null    object
 1   Url              398 non-null    object
 2   Telephone        342 non-null    object
 3   Longitude        544 non-null    float64
 4   Latitude         544 non-null    float64
 5   AddressRegion    540 non-null    object
 6   AddressLocality  384 non-null    object
 7   AddressCountry   542 non-null    object
 8   Tags             544 non-null    object
dtypes: float64(2), object(7)
memory usage: 38.4+ KB

In [12]:
import numpy as np

In [ ]:
#Rename Head of Column from Name to 'Tourist Attraction'

In [18]:
new_name = {'Name': 'Tourist Attraction'}

In [21]:
df.rename(columns = new_name)

,Tourist Attraction,Url,Telephone,Longitude,Latitude,AddressRegion,AddressLocality,AddressCountry,Tags
0,Ireland Writing Retreat Donegal,https://www.irelandwritingretreat.com,3.53833E+11,-8.232855,55.051496,Donegal,Gweedore,Ireland,"Learning,Activity Operator,Literary Ireland"
1,Swords Castle,https://swordscastle.events/,+353(0)1840 0891,-6.220338,53.459928,Dublin,Swords,Republic of Ireland,"Historic Houses and Castle,Castle,Tour"
2,Kilbolane Castle,https://visitballyhoura.com/explore/kilbolane-...,3536391300,-8.846867,52.337725,Cork,NaN,Ireland,"Historic Houses and Castle,Castle"
3,Spanish Point,NaN,NaN,-9.432739,52.842867,Clare,Spanish Point,Ireland,Discovery Point
4,Dunloe Castle,https://killarney.ie/listing/dunloe-castle,3.53647E+11,-9.627419,52.059671,Kerry,Beaufort,Republic of Ireland,"Castle,Historic Houses and Castle"
...,...,...,...,...,...,...,...,...,...
539,Macroom Buffalo Farm with O'Tuama Tours,https://www.otuamatours.ie,3.53869E+11,-9.247536,51.850410,Cork,Ballingeary,Republic of Ireland,"Food and Drink,Restaurant,Activity Operator,Vi..."
540,The Back Lane Pop Up Gallery,http://thebacklanegallery.blogspot.com/,3.53873E+11,-9.506293,52.058996,Kerry,Killarney,Ireland,"Craft,Shopping,Art Gallery"
541,Ferns Cathedral,https://www.archaeology.ie/monument-of-the-mon...,NaN,-6.492614,52.589983,Wexford,NaN,Ireland,"Church Abbey,Monastery,Churches,Abbeys and Mon..."
542,The Spire,NaN,NaN,-6.260294,53.350921,Dublin,Dublin City,Ireland,Public Sculpture
543,Courtown Beach,NaN,NaN,-6.226047,52.647958,Wexford,Courtown,Ireland,Beach

In [ ]:
#After some consideration, rename Address Region to County

In [29]:
new_name = {'AddressRegion': 'County'}

In [30]:
df.rename(columns = new_name)

,Name,Url,Telephone,Longitude,Latitude,County,AddressLocality,AddressCountry,Tags
0,Ireland Writing Retreat Donegal,https://www.irelandwritingretreat.com,3.53833E+11,-8.232855,55.051496,Donegal,Gweedore,Ireland,"Learning,Activity Operator,Literary Ireland"
1,Swords Castle,https://swordscastle.events/,+353(0)1840 0891,-6.220338,53.459928,Dublin,Swords,Republic of Ireland,"Historic Houses and Castle,Castle,Tour"
2,Kilbolane Castle,https://visitballyhoura.com/explore/kilbolane-...,3536391300,-8.846867,52.337725,Cork,NaN,Ireland,"Historic Houses and Castle,Castle"
3,Spanish Point,NaN,NaN,-9.432739,52.842867,Clare,Spanish Point,Ireland,Discovery Point
4,Dunloe Castle,https://killarney.ie/listing/dunloe-castle,3.53647E+11,-9.627419,52.059671,Kerry,Beaufort,Republic of Ireland,"Castle,Historic Houses and Castle"
...,...,...,...,...,...,...,...,...,...
539,Macroom Buffalo Farm with O'Tuama Tours,https://www.otuamatours.ie,3.53869E+11,-9.247536,51.850410,Cork,Ballingeary,Republic of Ireland,"Food and Drink,Restaurant,Activity Operator,Vi..."
540,The Back Lane Pop Up Gallery,http://thebacklanegallery.blogspot.com/,3.53873E+11,-9.506293,52.058996,Kerry,Killarney,Ireland,"Craft,Shopping,Art Gallery"
541,Ferns Cathedral,https://www.archaeology.ie/monument-of-the-mon...,NaN,-6.492614,52.589983,Wexford,NaN,Ireland,"Church Abbey,Monastery,Churches,Abbeys and Mon..."
542,The Spire,NaN,NaN,-6.260294,53.350921,Dublin,Dublin City,Ireland,Public Sculpture
543,Courtown Beach,NaN,NaN,-6.226047,52.647958,Wexford,Courtown,Ireland,Beach